#!/bin/bash
#SBATCH -N 8
#SBATCH -C gpu
#SBATCH -G 32
#SBATCH -J out_zPlane_4nm
#SBATCH -q regular
#SBATCH --mail-user=saurabhsawant@lbl.gov
#SBATCH --mail-type=ALL
#SBATCH -t 01:00:00
#SBATCH -A m3766_g
#SBATCH -o out_zPlane_4nm.o%j
#SBATCH -e out_zPlane_4nm.e%j
### SBATCH --reservation=weak_scaling_saurabh

#OpenMP settings:
export OMP_NUM_THREADS=1
export OMP_PLACES=threads
export OMP_PROC_BIND=spread


#run the application:
#applications may performance better with --gpu-bind=none instead of --gpu-bind=single:1 
srun -n 32 -c 32 --cpu_bind=cores -G 32 --gpu-bind=single:1  ../../../../Exec/main3d.gnu.MPI.CUDA.EB.TD.TRAN.BROYPRLL.HYPRE.ex ../../../../input/negf/point_charges/topgate_CNTFET_2Drand pc.Et=0.02 pc.V0=0.5 pc.mixing_factor=0.02 pc.charge_density=1.6e18 my_constants.Vgs_max=0.5 my_constants.Vgs_min=-1.6 my_constants.Nsteps=21 plot.folder_name=/global/cfs/projectdirs/m4540/eXstatic/point_charge/topgate_CNTFET/zPlaneVaried_alongHfO2Height_2Ddistrib/4nm use_diagnostics=1 pc.random_seed=0 my_constants.ZOffset=GO_bottom+4e-9 pc.flag_write_individual_charge_files=1
