#!/bin/bash
#SBATCH -N 32
#SBATCH -C gpu
#SBATCH -G 128
#SBATCH -J out_ChargeNum5
#SBATCH -q regular
#SBATCH --mail-user=saurabhsawant@lbl.gov
#SBATCH --mail-type=ALL
#SBATCH -t 01:00:00
#SBATCH -A m3766_g
#SBATCH -o out_ChargeNum5.o%j
#SBATCH -e out_ChargeNum5.e%j
### SBATCH --reservation=weak_scaling_saurabh

#OpenMP settings:
export OMP_NUM_THREADS=1
export OMP_PLACES=threads
export OMP_PROC_BIND=spread


#run the application:
#applications may performance better with --gpu-bind=none instead of --gpu-bind=single:1 
srun -n 128 -c 32 --cpu_bind=cores -G 128 --gpu-bind=single:1  ../../../../Exec/main3d.gnu.MPI.CUDA.EB.TD.TRAN.BROYPRLL.HYPRE.ex ../../../../input/negf/point_charges/topgate_CNTFET_singleCharge my_constants.Ef=-0.2 my_constants.Zoffset=0 my_constants.Xoffset=1e-9 pc.num=5 my_constants.periodicity_factor=3 my_constants.Vgs_max=1.0 my_constants.Vgs_min=-2 my_constants.Nsteps=31 plot.folder_name=/global/cfs/projectdirs/m3766/ELEQTRONeX/point_charge/topgate_CNTFET/crossCharge_1nmSpacing/ChargeNum5 use_diagnostics=1
