#!/bin/bash
#SBATCH -N 8
#SBATCH -C gpu
#SBATCH -G 32
#SBATCH -J out_Zoff4dz
#SBATCH -q regular
#SBATCH -t 04:00:00
#SBATCH -A m3766
#SBATCH -o out_Zoff4dz.o%j
#SBATCH -e out_Zoff4dz.e%j

#OpenMP settings:
export OMP_NUM_THREADS=1
export OMP_PLACES=threads
export OMP_PROC_BIND=spread


#run the application:
srun -n 32 -c 32 --cpu_bind=cores -G 32 ../../../../Exec/main3d.gnu.MPI.CUDA.EB.TD.TRAN.BROYPRLL.HYPRE.ex ../../../../input/negf/point_charges/topgate_CNTFET_cluster my_constants.Ef=-0.2 pc.num=1 my_constants.Vgs_max=1 my_constants.Vgs_min=-2 my_constants.Nsteps=31 plot.folder_name=/global/cfs/projectdirs/m3766/ELEQTRONeX/point_charge/topgate_CNTFET/singleCharge/EfmDot2/Zoff4dz use_diagnostics=1
