#!/bin/bash
#SBATCH -N 8
#SBATCH -C gpu
#SBATCH -G 32
#SBATCH -J out_rhoDot7_qFixed_ZcenterGO
#SBATCH -q regular
#SBATCH --mail-user=saurabhsawant@lbl.gov
#SBATCH --mail-type=ALL
#SBATCH -t 03:00:00
#SBATCH -A m3766_g
#SBATCH -o out_rhoDot7_qFixed_ZcenterGO.o%j
#SBATCH -e out_rhoDot7_qFixed_ZcenterGO.e%j
### SBATCH --reservation=weak_scaling_saurabh

#OpenMP settings:
export OMP_NUM_THREADS=1
export OMP_PLACES=threads
export OMP_PROC_BIND=spread


#run the application:
#applications may performance better with --gpu-bind=none instead of --gpu-bind=single:1 
srun -n 32 -c 32 --cpu_bind=cores -G 32 --gpu-bind=single:1  ../../../../Exec/main3d.gnu.MPI.CUDA.EB.TD.TRAN.BROYPRLL.HYPRE.ex ../../../../input/negf/point_charges/topgate_CNTFET_2Drand pc.flag_vary_occupation=0 pc.charge_density=0.7e18 my_constants.Vgs_max=0.6 my_constants.Vgs_min=-1 my_constants.Nsteps=9 plot.folder_name = /global/cfs/projectdirs/m3766/ELEQTRONeX/point_charge/topgate_CNTFET/rhoDot7_2D/qFixed_ZcenterGO use_diagnostics=1
